name: base
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - coverage
  - pytest
  - pytest-cov
  - coveralls
  - matplotlib
  - numpy
  - pandas
  - pip:
    - sphinxcontrib-bibtex
  - pyserial
  - pyvisa
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-jsmath
  - setuptools
  - wheel
  - pyyaml
